name: CI/CD Pipeline for Model Training
on:
    push:
        branches: [ main ]
    workflow_dispatch: {}

jobs:
    train-and-validate:
        strategy:
            fail-fast: false
            matrix:
                dataset: [ big, small ]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: pip install --upgrade pip && pip install -r requirements.txt

            - name: Train Model
              run: python3 train.py --dataset ${{ matrix.dataset }}

            - name: Log to MLflow and expose accuracy
              id: log_mlflow
              run: python3 log_to_mlflow.py

            - name: Deploy if validation passes
              if: ${{ fromJSON(steps.log_mlflow.outputs.accuracy) >= 0.9 }}
              run: |
                echo "Validation passed with accuracy ${{ steps.log_mlflow.outputs.accuracy }}."
                echo "Deploying model to... (demo)"

            - name: Fail if validation fails
              if: ${{ fromJSON(steps.log_mlflow.outputs.accuracy) < 0.9 }}
              run: |
                echo "Validation failed with accuracy ${{ steps.log_mlflow.outputs.accuracy }}."
                exit 1

            - name: Upload training artifacts
              if: always()  # Upload artifacts regardless of success or failure
              uses: actions/upload-artifact@v4
              with:
                name: outputs-${{ matrix.dataset }}
                path: |
                  metrics.json
                  model/
